############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Journals"
url = "/journals"
weight = 2

[[main]]
name = "Get Involved"
url = "/get-involved"
weight = 3
